app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, SaludConVozView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("accounts.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    #####################################################
    #path("cpqol/", include("core.urls")),
    path("pcatia/", include("pcatia.urls")),
    path('captcha/', include('captcha.urls')),
    #path("", home, name="home"),
    path("", SaludConVozView.as_view(), name="principal"),
]

app/core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", vista_formulario, name='cpqol'),
    path('exportar/', exportar_excel, name='exportar_excel'),

]

app/pcatia/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    # Vistas relacionadas al registro de la solicitud
    HomeView,
    SolicitudCreateView,
    SolicitudReviewView,
    SolicitudUpdateView,
    SolicitudConfirmView,

    # Vistas relacionadas al perfil de admin    
    SolicitudListView, 
    SolicitudDeleteView, 
    SolicitudDetailView, 
    GenerarDocumentoView, 
    DescargarDocumentoView
)

app_name = 'pcatia'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('solicitud/', SolicitudCreateView.as_view(), name='crear_solicitud'),
    path('review/', SolicitudReviewView.as_view(), name='solicitud_review'),
    path('edit/', SolicitudUpdateView.as_view(), name='solicitud_edit'),
    path('confirmar/', SolicitudConfirmView.as_view(), name='solicitud_confirmar'),    
    path('solicitudes/', SolicitudListView.as_view(), name='solicitud_list'),
    path('<int:pk>/', SolicitudDetailView.as_view(), name='solicitud_detail'),    
    path('<int:pk>/borrar/', SolicitudDeleteView.as_view(), name='solicitud_delete'),
    path('generar_documento/<int:pk>/', GenerarDocumentoView.as_view(), name='generar_documento'),
    path('descargar_documento/<str:file_name>/', DescargarDocumentoView.as_view(), name='descargar_documento'),    
]

app/templates/home/home.html
{% extends "_base.html" %} {% load static %} {% block contenido %}
<div class="d-flex align-items-center justify-content-center min-vh-100 text-center">
    <div class="card mx-auto" style="width: 80%;">
        <div class="card-body">
            <!-- Encabezado con los logos -->
            {% include 'logos.html' %}
            <!-- Título principal -->
            <h2 class="mb-4">¿Qué es Salud con voz?
            </h2>
            <!-- Contenido del texto -->
             
            <div class="text-start">
                <p>
                    Somos un grupo de docentes e investigadorxs de la 
                    <a href="https://ciess.sitios.fcm.unc.edu.ar/" target="_blank" >Universidad Nacional de Córdoba</a> y 
                    <a href="#">CONICET</a> que trabaja para conocer cómo nos sentimos con nuestra salud y cómo son nuestras experiencias de atención y cuidado de la salud.
                </p>
                <p>En este portal ofrecemos enlaces con información de nuestros trabajos, formularios 
                    para que puedan solicitarnos materiales y acceso a participantes de nuestros estudios. </p>
                
                <h5 class="mt-4">¿Estás buscando un cuestionario?</h5>
                <p>Estas son las herramientas que tenemos a disposición:</p>
                <ul>
                    <li>
                        <strong>Herramientas PCATIA para valorar la atención primaria de la salud</strong>
                        <ul>
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/pcatia/" target="_blank">Información sobre PCATIA </a></li>
                            
                        </ul>
                        <div><a href="{% url 'pcatia:home' %} " class="btn" style="background-color: #8e44ad; color: white;"">Solicitar los cuestionarios PCATIA</a></div>
                    </li>
                    <br><br>
                    <li>
                        <strong>Cuestionarios de salud percibida o calidad de vida relacionada con la salud</strong>
                        <ul>
                           
                            
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/kidscreen/" target="_blank">KIDSCREEN: Calidad de vida en niñas, niños y jóvenes</a></li>
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/cpqol/" target="_blank">CP-QOL: Calidad de vida en personas con discapacidad motora</a></li>
                            <li><a href="#">DISABKIDS: Calidad de vida relacionada con la salud</a></li>
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/twvq/" target="_blank">TWVQ-AR: Vivencias de mujeres trans y percepción de su voz</a></li>
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/vhi/" target="_blank">CVHI: Vivencias de niñas y niños sobre la percepción de su voz</a></li>
                            <li><a href="https://ciess.sitios.fcm.unc.edu.ar/vrbq/" target="_blank">VRBQ: Resultados de la rehabilitación de trastornos vestibulares</a></li>
                            
                        </ul>
                    </li>
                    <div><a href="#" class="btn" style="background-color: #8e44ad; color: white;"">Solicitar cuestionario</a></div>
                </ul>
                <h5 class="mt-4">¿Te interesa participar en un estudio?</h5>
                

                <p>Estos son los estudios que estamos haciendo:</p>
                <ul>
                    <li><strong>Calidad de vida en personas con discapacidad motora en Argentina:</strong> 
                       </li>
                       <p>Descripción breve</p>
                       <p>Los indicadores de calidad de vida relacionada a la salud (CVRS) nos ayudan a conocer 
                        cómo se sienten las personas en aspectos relacionados a su salud y a los tratamientos 
                        e intervenciones que realizan para mejorar su salud. En las personas con discapacidad 
                        motora, estos indicadores pueden dar cuenta de distintos aspectos psicosociales y 
                        físicos que pueden verse comprometidos: ¿Cómo se sienten las personas en situaciones de 
                        participación social?, ¿cómo se sienten con su capacidad de movimiento? o ¿cómo influyen 
                        las distintas terapias en cómo se siente la persona? Los indicadores de CVRS nos pueden 
                        ayudar a orientar las terapias en base a las sensaciones y sentimientos de los usuarios
                         de los servicios de salud.</p>
                         <div>
                            <a href="#" class="btn" style="background-color: #8e44ad; color: white;"">Participar</a>
                         </div>
                         <br><br>
                         <li><strong>Valoración de atributos de atención primaria de la salud según profesionales, 
                            equipos y gestores de servicios / centros / clínicas.</strong></li>
                            <br><br>
                         <li>
                            <strong>Experiencias de usuarios de servicios / centros / clínicas: calidad de la atención de la salud.
                            </strong>
                         </li>
                </ul>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/home/index.html
{% extends '_base.html' %}

{% block contenido %}

        <div class="container px-2">

            <h1 class="mt-5">Cuestionarios cargados</h1>
            <div class="text-end">
                <a href="{% url 'cpqol' %}?seccion=0" class="btn btn-outline-primary ">Nuevo cuestionario</a>
                <a href="{% url 'exportar_excel' %}" class="btn btn-outline-success"><i class="bi-filetype-xlsx"></i></a>
            </div>
            <table class="table table-striped mt-5">
                <thead>
                    <tr>
                        <th>Código de participante</th>
                        <th>Fecha</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cuestionario in cuestionarios %}
                        <tr>
                            <td>{{cuestionario.codigo}}</td>
                            <td>{{cuestionario.creacion|date:"d/m/Y"}}</td>
                            <td class="text-center">
                                <a href="/cpqol/?seccion={{cuestionario.current_seccion}}&codigo={{cuestionario.codigo}}">
                                {% if cuestionario.confirmado %}
                                    <span class="badge bg-success">COMPLETADO</span>
                                {% else %}
                                    <i class="bi-pencil"></i>
                                {% endif %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

{% endblock %}