app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, SaludConVozView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("accounts.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    #####################################################
    #path("cpqol/", include("core.urls")),
    path("pcatia/", include("pcatia.urls")),
    path('captcha/', include('captcha.urls')),
    #path("", home, name="home"),
    path("", SaludConVozView.as_view(), name="principal"),
]

app/core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", vista_formulario, name='cpqol'),
    path('exportar/', exportar_excel, name='exportar_excel'),

]

app/pcatia/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    # Vistas relacionadas al registro de la solicitud
    HomeView,
    SolicitudCreateView,
    SolicitudReviewView,
    SolicitudUpdateView,
    SolicitudConfirmView,

    # Vistas relacionadas al perfil de admin    
    SolicitudListView, 
    SolicitudDeleteView, 
    SolicitudDetailView, 
    GenerarDocumentoView, 
    DescargarDocumentoView
)

app_name = 'pcatia'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('solicitud/', SolicitudCreateView.as_view(), name='crear_solicitud'),
    path('review/', SolicitudReviewView.as_view(), name='solicitud_review'),
    path('edit/', SolicitudUpdateView.as_view(), name='solicitud_edit'),
    path('confirmar/', SolicitudConfirmView.as_view(), name='solicitud_confirmar'),    
    path('solicitudes/', SolicitudListView.as_view(), name='solicitud_list'),
    path('<int:pk>/', SolicitudDetailView.as_view(), name='solicitud_detail'),    
    path('<int:pk>/borrar/', SolicitudDeleteView.as_view(), name='solicitud_delete'),
    path('generar_documento/<int:pk>/', GenerarDocumentoView.as_view(), name='generar_documento'),
    path('descargar_documento/<str:file_name>/', DescargarDocumentoView.as_view(), name='descargar_documento'),    
]

app/pcatia/models.py
from django.db import models
from django.utils import timezone

class Solicitud(models.Model):
    #Primero registro la fecha
    fecha_solicitud = models.DateTimeField(default=timezone.now)

    # Responsable principal
    nombres_principal = models.CharField(max_length=100)
    apellidos_principal = models.CharField(max_length=100)
    cargo_principal = models.CharField(max_length=100)
    institucion_principal = models.CharField(max_length=100)
    ciudad_principal = models.CharField(max_length=100)
    pais_principal = models.CharField(max_length=100)
    rol_estudio_principal = models.CharField(max_length=200)
    email_principal = models.EmailField()
    telefono_principal = models.CharField(max_length=20)    

    # Responsable alterno
    nombres_alterno = models.CharField(max_length=100)
    apellidos_alterno = models.CharField(max_length=100)
    cargo_alterno = models.CharField(max_length=100)
    institucion_alterno = models.CharField(max_length=100)
    ciudad_alterno = models.CharField(max_length=100)
    pais_alterno = models.CharField(max_length=100)
    rol_estudio_alterno = models.CharField(max_length=200)
    email_alterno = models.EmailField()
    telefono_alterno = models.CharField(max_length=20)

    # Información del estudio
    uso_curricular = models.CharField(max_length=3, choices=[('Sí', 'Sí'), ('No', 'No')], blank=False)
    carrera_posgrado = models.CharField(max_length=200, blank=True)
    estudiantes = models.CharField(max_length=200, blank=True)
    responsables_orientacion = models.CharField(max_length=200, blank=True)

    # Datos del proyecto
    titulo_estudio = models.CharField(max_length=200)
    objetivo = models.TextField(max_length=500)
    descripcion_metodologia = models.TextField(max_length=1500)
    caracteristicas_poblacion = models.TextField(max_length=500)
    utilidad_estudio = models.CharField(max_length=500)
    institucion_avala = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = "Solicitudes"

    def __str__(self):
        return f"{self.fecha_solicitud} - {self.apellidos_principal}, {self.nombres_principal}"

app/pcatia/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.files.storage import default_storage
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings

# Vistas
from django.views.generic import (DetailView, DeleteView, ListView, TemplateView, View, UpdateView, CreateView)
from django.views.generic.edit import FormView

# Models
from .models import Solicitud
from .forms import SolicitudForm

# Apps de terceros
from docxtpl import DocxTemplate
import uuid
import os


class HomeView(TemplateView):
    template_name = "pcatia/home.html"


class SolicitudCreateView(FormView):    
    form_class = SolicitudForm
    template_name = 'pcatia/solicitud_form.html'
    success_url = reverse_lazy('pcatia:solicitud_review')

    def form_valid(self, form):
        # Concatenar los campos del teléfono
        codigo_internacional = form.cleaned_data.get('codigo_internacional')
        codigo_area = form.cleaned_data.get('codigo_area')
        numero_telefono = form.cleaned_data.get('numero_telefono')

        codigo_internacional_alterno = form.cleaned_data.get('codigo_internacional_alterno')
        codigo_area_alterno = form.cleaned_data.get('codigo_area_alterno')
        numero_telefono_alterno = form.cleaned_data.get('numero_telefono_alterno')

        telefono_principal = f"{codigo_internacional} ({codigo_area}) {numero_telefono}"
        telefono_alterno = f"{codigo_internacional_alterno} ({codigo_area_alterno}) {numero_telefono_alterno}"

        # Asignar los valores concatenados a los campos del modelo
        solicitud = form.save(commit=False)
        solicitud.telefono_principal = telefono_principal
        solicitud.telefono_alterno = telefono_alterno

        self.request.session['form_data'] = form.cleaned_data
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print("Formulario es inválido")
        print(form.errors)  # Imprime los errores en la consola
        return super().form_invalid(form)


class SolicitudReviewView(TemplateView):    
    template_name = 'pcatia/solicitud_review.html'    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = self.request.session.get('form_data', {})
        return context
    
class SolicitudUpdateView(FormView):    
    form_class = SolicitudForm
    template_name = 'pcatia/solicitud_form.html'
    
    def get_form(self, form_class=None):
        # Prepopulate the form with data from the session
        form = super().get_form(form_class)
        form.initial = self.request.session.get('form_data', {})
        return form

    def form_valid(self, form):
        self.request.session['form_data'] = form.cleaned_data
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('pcatia:solicitud_review')
'''
class SolicitudConfirmView(TemplateView):    
    template_name = 'pcatia/solicitud_confirmar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = self.request.session.get('form_data', {})
        return context

    def post(self, request, *args, **kwargs):
        form_data = request.session.get('form_data', {})
        if form_data:
            # Save the form data to the database
            form_data.pop('captcha', None)  # Elimina 'captcha' si existe
            Solicitud.objects.create(**form_data)
            # Clear the session data
            request.session.pop('form_data', None)
        return self.render_to_response(self.get_context_data())
'''
class SolicitudConfirmView(TemplateView):    
    template_name = 'pcatia/solicitud_confirmar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = self.request.session.get('form_data', {})
        return context

    def post(self, request, *args, **kwargs):
        form_data = request.session.get('form_data', {})
        if form_data:            
            # Armar los campos de telefono
            telefono_principal = f"{form_data.get('codigo_internacional', '')} {form_data.get('codigo_area', '')} {form_data.get('numero_telefono', '')}"
            telefono_alterno = f"{form_data.get('codigo_internacional_alterno', '')} {form_data.get('codigo_area_alterno', '')} {form_data.get('numero_telefono_alterno', '')}"
            
            # Eliminar los campos desglosados del form_data
            form_data.pop('codigo_internacional', None)
            form_data.pop('codigo_area', None)
            form_data.pop('numero_telefono', None)
            form_data.pop('codigo_internacional_alterno', None)
            form_data.pop('codigo_area_alterno', None)
            form_data.pop('numero_telefono_alterno', None)

            # Agregar los teléfonos completos al form_data
            form_data['telefono_principal'] = telefono_principal
            form_data['telefono_alterno'] = telefono_alterno

            form_data.pop('captcha', None)  # Elimina 'captcha' si existe
            solicitud = Solicitud.objects.create(**form_data)

            # Enviar correo electrónico con los datos del formulario
            subject = 'Nueva solicitud recibida'
            # Renderizamos un template HTML para el contenido del email
            html_message = render_to_string('pcatia/email_template.html', {'solicitud': solicitud})
            plain_message = strip_tags(html_message)
            from_email = f'{settings.EMAIL_HOST_NAME} <{settings.EMAIL_HOST_USER}>'
            to = settings.EMAIL_RECEIVER

            send_mail(
                subject,
                plain_message,
                from_email,
                [to],
                html_message=html_message,  # Envía el mensaje HTML si el cliente lo soporta
                fail_silently=False,
            )

            # Clear the session data
            request.session.pop('form_data', None)
        
        return self.render_to_response(self.get_context_data())


class SolicitudListView(LoginRequiredMixin, ListView):
    model = Solicitud
    template_name = 'pcatia/solicitud_list.html'
    context_object_name = 'pcatia'    

class SolicitudDeleteView(LoginRequiredMixin, DeleteView):
    model = Solicitud
    template_name = 'pcatia/solicitud_confirm_delete.html'
    success_url = reverse_lazy('pcatia:solicitud_list')

class SolicitudDetailView(LoginRequiredMixin, DetailView):
    model = Solicitud
    template_name = 'pcatia/solicitud_detail.html'

# Generacion de docx
class GenerarDocumentoView(LoginRequiredMixin, DetailView):
    model = Solicitud
    template_name = 'pcatia/generar_documento.html'  

    def get(self, request, *args, **kwargs):
        solicitud = self.get_object()

        # Cargar la plantilla del archivo .docx
        template = DocxTemplate('templates/ActaUso.docx')

        # Definir el contexto con los datos del formulario
        contexto = {            
            'nombres_principal': solicitud.nombres_principal,
            'apellidos_principal': solicitud.apellidos_principal,
            'cargo_principal': solicitud.cargo_principal,
            'institucion_principal': solicitud.institucion_principal,
            'ciudad_principal': solicitud.ciudad_principal,
            'pais_principal': solicitud.pais_principal,
            'titulo_estudio': solicitud.titulo_estudio, 
            'caracteristicas_poblacion': solicitud.caracteristicas_poblacion,
            'dia_solicitud': solicitud.fecha_solicitud.day,
            'mes_solicitud': solicitud.fecha_solicitud.month,
            'anio_solicitud': solicitud.fecha_solicitud.year,          
        }

        # Rellenar la plantilla
        template.render(contexto)

        # Generar un nombre único para el archivo
        file_name = f'documento_{uuid.uuid4()}.docx'

        # Guardar el archivo temporalmente
        file_path = os.path.join('media', 'temp_docs', file_name)
        template.save(file_path)

        # Redirigir a la vista de descarga con el archivo generado
        return redirect('pcatia:descargar_documento', file_name=file_name)

class DescargarDocumentoView(LoginRequiredMixin, View):
    
    def get(self, request, file_name):
        file_path = os.path.join('media', 'temp_docs', file_name)

        # Comprobar si el archivo existe
        if default_storage.exists(file_path):
            # Crear una respuesta HTTP con el archivo
            with default_storage.open(file_path, 'rb') as docx_file:
                response = HttpResponse(docx_file.read(), content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
                response['Content-Disposition'] = f'attachment; filename={file_name}'
                return response
        else:
            return HttpResponse("El enlace ha expirado o el archivo ya no está disponible.", status=404)

app/templates/pcatia/generar_documento.html
{% extends "base.html" %}

{% block content %}
  <h2>Generación de Documento</h2>
  <p>El documento ha sido generado exitosamente. Puedes descargarlo en el siguiente enlace:</p>
  
  <a href="{% url 'descargar_documento' file_name=file_name %}">
    <button class="btn btn-primary">Descargar Documento</button>
  </a>

  <p><strong>Título del Estudio:</strong> {{ solicitud.titulo_estudio }}</p>
  <p><strong>Responsable Principal:</strong> {{ solicitud.nombres_principal }} {{ solicitud.apellidos_principal }}</p>
  <p><strong>Email Principal:</strong> {{ solicitud.email_principal }}</p>
  <p><strong>Fecha de Solicitud:</strong> {{ solicitud.fecha_solicitud|date:"d-m-Y" }}</p>
{% endblock %}

app/templates/pcatia/home.html
{% extends "_base.html" %} 
{% block contenido %}
<div class="d-flex align-items-center justify-content-center min-vh-100 text-left">
    <div class="card mx-auto" style="width: 75%;">
        <div class="card-body">
            <!-- Encabezado con los logos -->
            {% include 'logos.html' %}
            <!-- Título principal -->
            <h2 class="mb-4">Solicitud de instrumentos PCATIA
            </h2>
            <!-- Información sobre la colaboración y condiciones -->
    <!-- Contenido del texto -->
             
            <div class="text-start">
                <p class="mb-4">
                    La Colaboración PCATIA pone a disposición de la comunidad internacional el producto del trabajo de adaptación, actualización y armonización de los cuestionarios PCAT (Primary Care Assessment Tools) para ser aplicados en diferentes países de Iberoamérica.
                    El proceso realizado con participación de todos los grupos de investigación que al 2016 (fecha de inicio del proyecto) contaban con versiones adaptadas a su país (nueve) logró esta nueva generación de versiones que hemos denominado PCATIA en las
                    cuales hemos comprobado buena aceptabilidad lingüística de las poblaciones de todas las subregiones de Iberoamérica que utilizan la lengua española (Mesoamérica, Países andinos, Cono Sur e Iberia). La Colaboración PCATIA autoriza el uso de los
                    instrumentos PCATIA-A, PCATIA-C, PCATIA-G o PCATIA-P sin abonar arancel alguno. Al mismo tiempo requiere de las personas usuarias de PCATIA los siguientes compromisos, necesarios para la preservación de la fiabilidad del instrumento, así como
                    para el mantenimiento de la red de solidaridad en la cual se funda este trabajo:
                </p>
                <ul class="list-unstyled mb-4">
                    <li>1. No alterar el contenido de las escalas de cada dimensión, es decir, el número de ítems de cada apartado, la redacción de las preguntas ni las opciones de respuestas, ya que la validez interna, consistencia y equivalencia internacional de los
                        datos requiere del uso de los cuestionarios tal como se ofrecen.</li>
                    <li>2. Consultar a la Colaboración PCATIA en caso de necesitar introducir alguna modificación a los cuestionarios;</li>
                    <li>3. Mantener informadas a las coordinadoras de la Colaboración PCATIA de resultados, publicaciones derivadas y posibles cambios en los términos aquí manifestados.</li>
                    <li>4. Respetar y mencionar los créditos de autoría que aquí se mencionan: “Los cuestionarios PCATIA fueron producidos por el Grupo IA-PCAT, coordinado por las Profesoras Jacqueline Ponzo y Silvina Berra, a partir de la armonización de versiones adaptadas
                        del conjunto PCAT, desarrollado por la Prof. Barbara Starfield y el Dr. Leiyu Shi de Johns Hopkins University, USA”</li>
                </ul>
                <p class="mb-4">
                    Citando a tal fin las publicaciones que sean pertinentes, entre las cuales se sugiere:
                </p>
                <ul class="list-unstyled mb-4">
                    <li>Ponzo J, Berra S, Giraldo Osorio A, Pasarín MI, Leyns C, Vélez Álvarez C, Soto Chávez CA, Molina V, Fuentes-García A, Hauser L, grupo de trabajo IA-PCAT. Armonización iberoamericana de los instrumentos PCAT para la evaluación del primer nivel.
                        Revista Panamericana de Salud Pública. 2018;42:e80. <a href="https://doi.org/10.26633/RPSP.2018.80" target="_blank">https://doi.org/10.26633/RPSP.2018.80</a></li>
                    <li>Berra S, Rivadero L; Grupo IA-PCAT; Otros investigadores del Grupo IA-PCAT. Aceptabilidad lingüística en la comprensión de cuestionarios de valoración de servicios de salud en Iberoamérica. [published online ahead of print, 2020 Jul 9]. Gac Sanit.
                        2020; S0213-9111(20)30123-0. <a href="https://doi.org/10.1016/j.gaceta.2020.04.019" target="_blank">doi:10.1016/j.gaceta.2020.04.019</a></li>
                    <li>Página web: <a href="http://ciess.webs.fcm.unc.edu.ar/ia-pcat/" target="_blank">http://ciess.webs.fcm.unc.edu.ar/ia-pcat/</a></li>
                </ul>
                <p class="mb-4">
                    Apelando a la misma solidaridad con la que la Colaboración PCATIA realizó este trabajo para poner a disposición los instrumentos, se solicita a quienes los utilicen que faciliten el uso de datos obtenidos (con la anonimización necesaria) para conformar
                    bases de datos colaborativas internacionales que permitan realizar análisis de propiedades métricas y comparaciones internacionales.
                </p>
                <a href="{% url 'pcatia:crear_solicitud' %}" class="btn btn-warning">Ir al formulario</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/pcatia/solicitud_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>¿Estás seguro de que deseas borrar la solicitud "{{ object }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Sí, borrar</button>
    <a href="{% url 'pcatia:solicitud_list' %}">Cancelar</a>
  </form>
{% endblock %}

app/templates/pcatia/solicitud_detail.html
{% extends "base_login.html" %}

{% block content %}

<div class="d-flex align-items-center justify-content-center min-vh-100 text-left">
  <div class="card mx-auto" style="width: 90%;">
      <div class="card-body">
          <!-- Encabezado con los logos -->
          {% include 'logos.html' %}
         
  <!-- Contenido del texto -->
           
          <div class="text-start">

  <h2>Detalle de la Solicitud</h2>
  <p><strong>Fecha de Solicitud:</strong> {{ solicitud.fecha_solicitud }}</p>
  
  <!-- Información de contacto principal -->
  <h3>Responsable Principal de la Aplicación</h3>
  <p><strong>Nombres:</strong> {{ solicitud.nombres_principal }}</p>
  <p><strong>Apellidos:</strong> {{ solicitud.apellidos_principal }}</p>
  <p><strong>Cargo:</strong> {{ solicitud.cargo_principal }}</p>
  <p><strong>Institución:</strong> {{ solicitud.institucion_principal }}</p>
  <p><strong>Ciudad o Localidad:</strong> {{ solicitud.ciudad_principal }}</p>
  <p><strong>País:</strong> {{ solicitud.pais_principal }}</p>
  <p><strong>Rol en el Estudio:</strong> {{ solicitud.rol_estudio_principal }}</p>
  <p><strong>Correo Electrónico:</strong> {{ solicitud.email_principal }}</p>
  <p><strong>Teléfono Celular:</strong> {{ solicitud.telefono_principal }}</p>

  <!-- Información de contacto secundario -->
  <h3>Responsable Alterno de la Aplicación</h3>
  <p><strong>Nombres:</strong> {{ solicitud.nombres_alterno }}</p>
  <p><strong>Apellidos:</strong> {{ solicitud.apellidos_alterno }}</p>
  <p><strong>Cargo:</strong> {{ solicitud.cargo_alterno }}</p>
  <p><strong>Institución:</strong> {{ solicitud.institucion_alterno }}</p>
  <p><strong>Ciudad o Localidad:</strong> {{ solicitud.ciudad_alterno }}</p>
  <p><strong>País:</strong> {{ solicitud.pais_alterno }}</p>
  <p><strong>Rol en el Estudio:</strong> {{ solicitud.rol_estudio_alterno }}</p>
  <p><strong>Correo Electrónico:</strong> {{ solicitud.email_alterno }}</p>
  <p><strong>Teléfono Celular:</strong> {{ solicitud.telefono_alterno }}</p>

  <!-- Uso curricular de los instrumentos -->
  <h3>Uso Curricular de los Instrumentos</h3>
  <p><strong>¿Forma parte de un estudio curricular?:</strong> {{ solicitud.uso_curricular }}</p>
  <p><strong>Carrera de Posgrado:</strong> {{ solicitud.carrera_posgrado }}</p>
  <p><strong>Estudiantes:</strong> {{ solicitud.estudiantes }}</p>
  <p><strong>Responsables de Orientación:</strong> {{ solicitud.responsables_orientacion }}</p>

  <!-- Datos del proyecto -->
  <h3>Datos del Proyecto</h3>
  <p><strong>Título o Tema del Estudio:</strong> {{ solicitud.titulo_estudio }}</p>
  <p><strong>Objetivo:</strong> {{ solicitud.objetivo }}</p>
  <p><strong>Descripción de la Metodología:</strong> {{ solicitud.descripcion_metodologia }}</p>
  <p><strong>Características de la Población:</strong> {{ solicitud.caracteristicas_poblacion }}</p>
  <p><strong>Utilidad del Estudio:</strong> {{ solicitud.utilidad_estudio }}</p>
  <p><strong>Institución que Avala:</strong> {{ solicitud.institucion_avala }}</p>
  <br>
  <a href="{% url 'pcatia:generar_documento' solicitud.id %}"><button>Generar Acta</button></a>
  <br>
  
  <!-- Botón para volver al listado -->
  <a href="{% url 'pcatia:solicitud_list' %}"><button>Volver al Listado</button></a>
        </div>
      </div>
    </div>
</div>
{% endblock %}

app/templates/pcatia/solicitud_list.html
{% extends "base_login.html" %}

{% block content %}
  <h2>Listado de Solicitudes</h2>
  <table class="table table-striped">
    <thead>
      <tr>        
        <th>Responsable Principal</th>
        <th>Email Principal</th>
        <th>Institución Principal</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for solicitud in pcatia %}
        <tr>         
          <td>{{ solicitud.nombres_principal }} {{ solicitud.apellidos_principal }}</td>
          <td>{{ solicitud.email_principal }}</td>
          <td>{{ solicitud.institucion_principal }}</td>
          <td>
            <a href="{% url 'pcatia:solicitud_detail' solicitud.id %}">
              <button>Ver</button>
            </a>            
            <a href="{% url 'pcatia:solicitud_delete' solicitud.id %}">
              <button>Borrar</button>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/pcatia/solicitud_review.html
{% extends "base.html" %}

{% block content %}
  
<div class="d-flex align-items-center justify-content-center min-vh-100 text-left">
  <div class="card mx-auto" style="width: 90%;">
      <div class="card-body">
          <!-- Encabezado con los logos -->
          {% include 'logos.html' %}
         
  <!-- Contenido del texto -->
           
          <div class="text-start">
<form action="{% url 'pcatia:solicitud_confirmar' %}" method="post">
  {% csrf_token %}
  <h2>Detalle de la solicitud</h2>
  
  
  <!-- Información de contacto principal -->
  <h4>Responsable Principal de la Aplicación</h4>
  <p><strong>Nombres:</strong> {{ form_data.nombres_principal }}</p>
  <p><strong>Apellidos:</strong> {{ form_data.apellidos_principal }}</p>
  <p><strong>Cargo:</strong> {{ form_data.cargo_principal }}</p>
  <p><strong>Institución:</strong> {{ form_data.institucion_principal }}</p>
  <p><strong>Ciudad o Localidad:</strong> {{ form_data.ciudad_principal }}</p>
  <p><strong>País:</strong> {{ form_data.pais_principal }}</p>
  <p><strong>Rol en el Estudio:</strong> {{ form_data.rol_estudio_principal }}</p>
  <p><strong>Correo Electrónico:</strong> {{ form_data.email_principal }}</p>
  <p><strong>Teléfono Celular:</strong> {{ form_data.telefono_principal }}</p>

  <!-- Información de contacto secundario -->
  <h4>Responsable Alterno de la Aplicación</h4>
  <p><strong>Nombres:</strong> {{ form_data.nombres_alterno }}</p>
  <p><strong>Apellidos:</strong> {{ form_data.apellidos_alterno }}</p>
  <p><strong>Cargo:</strong> {{ form_data.cargo_alterno }}</p>
  <p><strong>Institución:</strong> {{ form_data.institucion_alterno }}</p>
  <p><strong>Ciudad o Localidad:</strong> {{ form_data.ciudad_alterno }}</p>
  <p><strong>País:</strong> {{ form_data.pais_alterno }}</p>
  <p><strong>Rol en el Estudio:</strong> {{ form_data.rol_estudio_alterno }}</p>
  <p><strong>Correo Electrónico:</strong> {{ form_data.email_alterno }}</p>
  <p><strong>Teléfono Celular:</strong> {{ form_data.telefono_alterno }}</p>

  <!-- Uso curricular de los instrumentos -->
  <h4>Uso Curricular de los Instrumentos</h4>
  <p><strong>¿Forma parte de un estudio curricular?:</strong> {{ form_data.uso_curricular }}</p>
  {% if form_data.uso_curricular == "Sí" %}
    <p><strong>Carrera de Posgrado:</strong> {{ form_data.carrera_posgrado }}</p>
    <p><strong>Estudiantes:</strong> {{ form_data.estudiantes }}</p>
    <p><strong>Responsables de Orientación:</strong> {{ form_data.responsables_orientacion }}</p>
{% endif %}

  <!-- Datos del proyecto -->
  <h4>Datos del Proyecto</h4>
  <p><strong>Título o Tema del Estudio:</strong> {{ form_data.titulo_estudio }}</p>
  <p><strong>Objetivo:</strong> {{ form_data.objetivo }}</p>
  <p><strong>Descripción de la Metodología:</strong> {{ form_data.descripcion_metodologia }}</p>
  <p><strong>Características de la Población:</strong> {{ form_data.caracteristicas_poblacion }}</p>
  <p><strong>Utilidad del Estudio:</strong> {{ form_data.utilidad_estudio }}</p>
  <p><strong>Institución que Avala:</strong> {{ form_data.institucion_avala }}</p>
  <button type="submit" class="btn btn-success">Confirmar</button>
</form>
<br>
<a href="{% url 'pcatia:solicitud_edit' %}" class="btn btn-warning">Editar</a>

</div>
</div>
</div>
</div>
{% endblock %}