app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, SaludConVozView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("accounts.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    #####################################################
    #path("cpqol/", include("core.urls")),
    path("pcatia/", include("pcatia.urls")),
    path('captcha/', include('captcha.urls')),
    #path("", home, name="home"),
    path("", SaludConVozView.as_view(), name="principal"),
]

app/core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", vista_formulario, name='cpqol'),
    path('exportar/', exportar_excel, name='exportar_excel'),

]

app/pcatia/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    # Vistas relacionadas al registro de la solicitud
    HomeView,
    SolicitudCreateView,
    SolicitudReviewView,
    SolicitudUpdateView,
    SolicitudConfirmView,

    # Vistas relacionadas al perfil de admin    
    SolicitudListView, 
    SolicitudDeleteView, 
    SolicitudDetailView, 
    GenerarDocumentoView, 
    DescargarDocumentoView
)

app_name = 'pcatia'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('solicitud/', SolicitudCreateView.as_view(), name='crear_solicitud'),
    path('review/', SolicitudReviewView.as_view(), name='solicitud_review'),
    path('edit/', SolicitudUpdateView.as_view(), name='solicitud_edit'),
    path('confirmar/', SolicitudConfirmView.as_view(), name='solicitud_confirmar'),    
    path('solicitudes/', SolicitudListView.as_view(), name='solicitud_list'),
    path('<int:pk>/', SolicitudDetailView.as_view(), name='solicitud_detail'),    
    path('<int:pk>/borrar/', SolicitudDeleteView.as_view(), name='solicitud_delete'),
    path('generar_documento/<int:pk>/', GenerarDocumentoView.as_view(), name='generar_documento'),
    path('descargar_documento/<str:file_name>/', DescargarDocumentoView.as_view(), name='descargar_documento'),    
]

app/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Salud con Voz</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="shortcut icon" href='{% static "img/favicon.ico" %}'>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />      
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        {% block assets %}{% endblock %}

    </head>
    <body>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                <a class="navbar-brand " href="{% url 'principal' %}">
                    <img src="{% static 'img/logo-scv.png' %}" height="60" alt="Logo de Salud con Voz">
                </a>
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.first_name %}{{user.first_name}}{% else %}{{user.username}}{% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <!-- <li><a class="dropdown-item" href="#">Bases de datos</a></li> -->
                            <li><a class="dropdown-item" href="#">Perfil</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><form action="{% url 'logout' %}" method="post">{% csrf_token %}<button type="submit" class="dropdown-item">Cerrar sesión</button></form></li>
                        </ul>
                    </div>
                </div>
            </nav>        
        {% endif %}
        
        {% block contenido %}
        {% endblock %}

    </body>
</html>

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Salud Con Voz{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/base_login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PCATIA - Admin zone{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'principal' %}">Inicio</a>
        <div class="collapse navbar-collapse">
            <!-- Navegación -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pcatia:solicitud_list' %}">Solicitudes</a>
                </li>
                <!-- Agrega más elementos de navegación aquí -->
            </ul>
            <div class="form-inline my-2 my-lg-0">
                <!-- Botón de logout -->
                 <!--<a href="{% url 'logout' %}" class="btn btn-danger my-2 my-sm-0">Logout</a>-->
                <form action="{% url 'logout' %}" method="post">{% csrf_token %}<button class="btn my-2 my-sm-0" style="background-color: #8e44ad; color: white;" type="submit">Cerrar sesión</button></form></li>
                
            </div>
        </div>
    </nav>
    
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS y dependencias -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.8/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

app/templates/logos.html
{% load static %}

<!-- templates/logos.html -->
<div class="d-flex justify-content-center mb-4">
    <img src="{% static 'img/logo-ciecs.png' %}" height="80" alt="Logo CIECS" class="me-3">
    <img src="{% static 'img/logo-scv.png' %}" height="80" alt="Logo Salud con Voz">
</div>